# -*- coding: utf-8 -*-
"""weather_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1Vo2EuSgsLfATDgJnq-NqGRAg2MFfMe
"""

import pandas as pd

weather = pd.read_csv("weather.csv", index_col="DATE")

weather

null_pct = weather.apply(pd.isnull).sum()/weather.shape[0]

null_pct

valid_columns = weather.columns[null_pct < 0.05]

valid_columns

weather = weather[valid_columns].copy()

weather.columns = weather.columns.str.lower()

weather

weather = weather.ffill()

weather.apply(pd.isnull).sum()

weather.dtypes

weather.index

weather.index = pd.to_datetime(weather.index)

weather.index

weather.index.year.value_counts().sort_index()

weather["prcp"].plot()

weather

weather["target"] = weather.shift(-1)["tmax"]

weather

weather = weather.ffill()

weather

from sklearn.linear_model import Ridge

rr = Ridge(alpha=0.1)

predictors = weather.columns[~weather.columns.isin(["target", "name", "station"])]

predictors

def backtest(weather, model, predictors, start=3650, step=90):
  all_predictions = []

  for i in range(start, weather.shape[0], step):
    train = weather.iloc[:i,:]
    test = weather.iloc[i:(i+step), :]

    model.fit(train[predictors], train["target"])

    preds = model.predict(test[predictors])

    preds = pd.Series(preds, index=test.index)

    combined = pd.concat([test["target"], preds], axis=1)

    combined.columns = ["actual", "prediction"]

    combined["diff"] = (combined["prediction"] - combined["actual"]).abs()

    all_predictions.append(combined)

  return pd.concat(all_predictions, axis=0)

predictions = backtest(weather, rr, predictors)

predictions

from sklearn.metrics import mean_absolute_error

mean_absolute_error(predictions["actual"], predictions["prediction"])

def pct_diff(old, new):
  return (new - old) / old

def compute_rolling(weather, horizon, col):
  label = f"rolling_{horizon}_{col}"
  weather[label] = weather[col].rolling(horizon).mean()
  weather[f"pct_diff_{label}"] = pct_diff(weather[label], weather[col])
  return weather

rolling_horizons = [3,14]

for horizon in rolling_horizons:
  for col in ["tmax", "tmin", "prcp"]:
    weather = compute_rolling(weather, horizon, col)

weather

weather = weather.iloc[14:,:]

weather

weather = weather.fillna(0)

weather

def expand_mean(df):
  return df.expanding(1).mean()

for col in ["tmax", "tmin", "prcp"]:
  weather[f"month_avg_{col}"] = weather[col].groupby(weather.index.month, group_keys=False).apply(expand_mean)
  weather[f"day_avg_{col}"] = weather[col].groupby(weather.index.day_of_year, group_keys=False).apply(expand_mean)

weather

predictors = weather.columns[~weather.columns.isin(["target", "name", "station"])]

predictors

predictions = backtest(weather, rr, predictors)

mean_absolute_error(predictions["actual"], predictions["prediction"])

predictions.sort_values("diff", ascending=False)

predictions["diff"].round().value_counts().sort_index().plot()

